// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serverpb.proto

package serverpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RawGetRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetRequest) Reset()         { *m = RawGetRequest{} }
func (m *RawGetRequest) String() string { return proto.CompactTextString(m) }
func (*RawGetRequest) ProtoMessage()    {}
func (*RawGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{0}
}

func (m *RawGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetRequest.Unmarshal(m, b)
}
func (m *RawGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetRequest.Marshal(b, m, deterministic)
}
func (m *RawGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetRequest.Merge(m, src)
}
func (m *RawGetRequest) XXX_Size() int {
	return xxx_messageInfo_RawGetRequest.Size(m)
}
func (m *RawGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetRequest proto.InternalMessageInfo

func (m *RawGetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type RawGetResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetResponse) Reset()         { *m = RawGetResponse{} }
func (m *RawGetResponse) String() string { return proto.CompactTextString(m) }
func (*RawGetResponse) ProtoMessage()    {}
func (*RawGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{1}
}

func (m *RawGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetResponse.Unmarshal(m, b)
}
func (m *RawGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetResponse.Marshal(b, m, deterministic)
}
func (m *RawGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetResponse.Merge(m, src)
}
func (m *RawGetResponse) XXX_Size() int {
	return xxx_messageInfo_RawGetResponse.Size(m)
}
func (m *RawGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetResponse proto.InternalMessageInfo

func (m *RawGetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RawGetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type RawBatchGetRequest struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawBatchGetRequest) Reset()         { *m = RawBatchGetRequest{} }
func (m *RawBatchGetRequest) String() string { return proto.CompactTextString(m) }
func (*RawBatchGetRequest) ProtoMessage()    {}
func (*RawBatchGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{2}
}

func (m *RawBatchGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawBatchGetRequest.Unmarshal(m, b)
}
func (m *RawBatchGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawBatchGetRequest.Marshal(b, m, deterministic)
}
func (m *RawBatchGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawBatchGetRequest.Merge(m, src)
}
func (m *RawBatchGetRequest) XXX_Size() int {
	return xxx_messageInfo_RawBatchGetRequest.Size(m)
}
func (m *RawBatchGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawBatchGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawBatchGetRequest proto.InternalMessageInfo

func (m *RawBatchGetRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type RawBatchGetResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Values               [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawBatchGetResponse) Reset()         { *m = RawBatchGetResponse{} }
func (m *RawBatchGetResponse) String() string { return proto.CompactTextString(m) }
func (*RawBatchGetResponse) ProtoMessage()    {}
func (*RawBatchGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{3}
}

func (m *RawBatchGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawBatchGetResponse.Unmarshal(m, b)
}
func (m *RawBatchGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawBatchGetResponse.Marshal(b, m, deterministic)
}
func (m *RawBatchGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawBatchGetResponse.Merge(m, src)
}
func (m *RawBatchGetResponse) XXX_Size() int {
	return xxx_messageInfo_RawBatchGetResponse.Size(m)
}
func (m *RawBatchGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawBatchGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawBatchGetResponse proto.InternalMessageInfo

func (m *RawBatchGetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RawBatchGetResponse) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type RawPutRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutRequest) Reset()         { *m = RawPutRequest{} }
func (m *RawPutRequest) String() string { return proto.CompactTextString(m) }
func (*RawPutRequest) ProtoMessage()    {}
func (*RawPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{4}
}

func (m *RawPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutRequest.Unmarshal(m, b)
}
func (m *RawPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutRequest.Marshal(b, m, deterministic)
}
func (m *RawPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutRequest.Merge(m, src)
}
func (m *RawPutRequest) XXX_Size() int {
	return xxx_messageInfo_RawPutRequest.Size(m)
}
func (m *RawPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutRequest proto.InternalMessageInfo

func (m *RawPutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawPutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type RawPutResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutResponse) Reset()         { *m = RawPutResponse{} }
func (m *RawPutResponse) String() string { return proto.CompactTextString(m) }
func (*RawPutResponse) ProtoMessage()    {}
func (*RawPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{5}
}

func (m *RawPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutResponse.Unmarshal(m, b)
}
func (m *RawPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutResponse.Marshal(b, m, deterministic)
}
func (m *RawPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutResponse.Merge(m, src)
}
func (m *RawPutResponse) XXX_Size() int {
	return xxx_messageInfo_RawPutResponse.Size(m)
}
func (m *RawPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutResponse proto.InternalMessageInfo

func (m *RawPutResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RawBatchPutRequest struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values               [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawBatchPutRequest) Reset()         { *m = RawBatchPutRequest{} }
func (m *RawBatchPutRequest) String() string { return proto.CompactTextString(m) }
func (*RawBatchPutRequest) ProtoMessage()    {}
func (*RawBatchPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{6}
}

func (m *RawBatchPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawBatchPutRequest.Unmarshal(m, b)
}
func (m *RawBatchPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawBatchPutRequest.Marshal(b, m, deterministic)
}
func (m *RawBatchPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawBatchPutRequest.Merge(m, src)
}
func (m *RawBatchPutRequest) XXX_Size() int {
	return xxx_messageInfo_RawBatchPutRequest.Size(m)
}
func (m *RawBatchPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawBatchPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawBatchPutRequest proto.InternalMessageInfo

func (m *RawBatchPutRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *RawBatchPutRequest) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type RawBatchPutResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawBatchPutResponse) Reset()         { *m = RawBatchPutResponse{} }
func (m *RawBatchPutResponse) String() string { return proto.CompactTextString(m) }
func (*RawBatchPutResponse) ProtoMessage()    {}
func (*RawBatchPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{7}
}

func (m *RawBatchPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawBatchPutResponse.Unmarshal(m, b)
}
func (m *RawBatchPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawBatchPutResponse.Marshal(b, m, deterministic)
}
func (m *RawBatchPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawBatchPutResponse.Merge(m, src)
}
func (m *RawBatchPutResponse) XXX_Size() int {
	return xxx_messageInfo_RawBatchPutResponse.Size(m)
}
func (m *RawBatchPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawBatchPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawBatchPutResponse proto.InternalMessageInfo

func (m *RawBatchPutResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RawDeleteRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteRequest) Reset()         { *m = RawDeleteRequest{} }
func (m *RawDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RawDeleteRequest) ProtoMessage()    {}
func (*RawDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{8}
}

func (m *RawDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteRequest.Unmarshal(m, b)
}
func (m *RawDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RawDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteRequest.Merge(m, src)
}
func (m *RawDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RawDeleteRequest.Size(m)
}
func (m *RawDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteRequest proto.InternalMessageInfo

func (m *RawDeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type RawDeleteResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteResponse) Reset()         { *m = RawDeleteResponse{} }
func (m *RawDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*RawDeleteResponse) ProtoMessage()    {}
func (*RawDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{9}
}

func (m *RawDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteResponse.Unmarshal(m, b)
}
func (m *RawDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteResponse.Marshal(b, m, deterministic)
}
func (m *RawDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteResponse.Merge(m, src)
}
func (m *RawDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_RawDeleteResponse.Size(m)
}
func (m *RawDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteResponse proto.InternalMessageInfo

func (m *RawDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RawBatchDeleteRequest struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawBatchDeleteRequest) Reset()         { *m = RawBatchDeleteRequest{} }
func (m *RawBatchDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RawBatchDeleteRequest) ProtoMessage()    {}
func (*RawBatchDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{10}
}

func (m *RawBatchDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawBatchDeleteRequest.Unmarshal(m, b)
}
func (m *RawBatchDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawBatchDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RawBatchDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawBatchDeleteRequest.Merge(m, src)
}
func (m *RawBatchDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RawBatchDeleteRequest.Size(m)
}
func (m *RawBatchDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawBatchDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawBatchDeleteRequest proto.InternalMessageInfo

func (m *RawBatchDeleteRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type RawBatchDeleteResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawBatchDeleteResponse) Reset()         { *m = RawBatchDeleteResponse{} }
func (m *RawBatchDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*RawBatchDeleteResponse) ProtoMessage()    {}
func (*RawBatchDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{11}
}

func (m *RawBatchDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawBatchDeleteResponse.Unmarshal(m, b)
}
func (m *RawBatchDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawBatchDeleteResponse.Marshal(b, m, deterministic)
}
func (m *RawBatchDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawBatchDeleteResponse.Merge(m, src)
}
func (m *RawBatchDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_RawBatchDeleteResponse.Size(m)
}
func (m *RawBatchDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawBatchDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawBatchDeleteResponse proto.InternalMessageInfo

func (m *RawBatchDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RawDeleteRangeRequest struct {
	StartKey             []byte   `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey               []byte   `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteRangeRequest) Reset()         { *m = RawDeleteRangeRequest{} }
func (m *RawDeleteRangeRequest) String() string { return proto.CompactTextString(m) }
func (*RawDeleteRangeRequest) ProtoMessage()    {}
func (*RawDeleteRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{12}
}

func (m *RawDeleteRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteRangeRequest.Unmarshal(m, b)
}
func (m *RawDeleteRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteRangeRequest.Marshal(b, m, deterministic)
}
func (m *RawDeleteRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteRangeRequest.Merge(m, src)
}
func (m *RawDeleteRangeRequest) XXX_Size() int {
	return xxx_messageInfo_RawDeleteRangeRequest.Size(m)
}
func (m *RawDeleteRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteRangeRequest proto.InternalMessageInfo

func (m *RawDeleteRangeRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *RawDeleteRangeRequest) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

type RawDeleteRangeResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteRangeResponse) Reset()         { *m = RawDeleteRangeResponse{} }
func (m *RawDeleteRangeResponse) String() string { return proto.CompactTextString(m) }
func (*RawDeleteRangeResponse) ProtoMessage()    {}
func (*RawDeleteRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{13}
}

func (m *RawDeleteRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteRangeResponse.Unmarshal(m, b)
}
func (m *RawDeleteRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteRangeResponse.Marshal(b, m, deterministic)
}
func (m *RawDeleteRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteRangeResponse.Merge(m, src)
}
func (m *RawDeleteRangeResponse) XXX_Size() int {
	return xxx_messageInfo_RawDeleteRangeResponse.Size(m)
}
func (m *RawDeleteRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteRangeResponse proto.InternalMessageInfo

func (m *RawDeleteRangeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RawScanRequest struct {
	StartKey             []byte   `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey               []byte   `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawScanRequest) Reset()         { *m = RawScanRequest{} }
func (m *RawScanRequest) String() string { return proto.CompactTextString(m) }
func (*RawScanRequest) ProtoMessage()    {}
func (*RawScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{14}
}

func (m *RawScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawScanRequest.Unmarshal(m, b)
}
func (m *RawScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawScanRequest.Marshal(b, m, deterministic)
}
func (m *RawScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawScanRequest.Merge(m, src)
}
func (m *RawScanRequest) XXX_Size() int {
	return xxx_messageInfo_RawScanRequest.Size(m)
}
func (m *RawScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawScanRequest proto.InternalMessageInfo

func (m *RawScanRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *RawScanRequest) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

func (m *RawScanRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RawScanResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Keys                 [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Values               [][]byte `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawScanResponse) Reset()         { *m = RawScanResponse{} }
func (m *RawScanResponse) String() string { return proto.CompactTextString(m) }
func (*RawScanResponse) ProtoMessage()    {}
func (*RawScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{15}
}

func (m *RawScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawScanResponse.Unmarshal(m, b)
}
func (m *RawScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawScanResponse.Marshal(b, m, deterministic)
}
func (m *RawScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawScanResponse.Merge(m, src)
}
func (m *RawScanResponse) XXX_Size() int {
	return xxx_messageInfo_RawScanResponse.Size(m)
}
func (m *RawScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawScanResponse proto.InternalMessageInfo

func (m *RawScanResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RawScanResponse) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *RawScanResponse) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type RawReverseScanRequest struct {
	StartKey             []byte   `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey               []byte   `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawReverseScanRequest) Reset()         { *m = RawReverseScanRequest{} }
func (m *RawReverseScanRequest) String() string { return proto.CompactTextString(m) }
func (*RawReverseScanRequest) ProtoMessage()    {}
func (*RawReverseScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{16}
}

func (m *RawReverseScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawReverseScanRequest.Unmarshal(m, b)
}
func (m *RawReverseScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawReverseScanRequest.Marshal(b, m, deterministic)
}
func (m *RawReverseScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawReverseScanRequest.Merge(m, src)
}
func (m *RawReverseScanRequest) XXX_Size() int {
	return xxx_messageInfo_RawReverseScanRequest.Size(m)
}
func (m *RawReverseScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawReverseScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawReverseScanRequest proto.InternalMessageInfo

func (m *RawReverseScanRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *RawReverseScanRequest) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

func (m *RawReverseScanRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RawReverseScanResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Keys                 [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Values               [][]byte `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawReverseScanResponse) Reset()         { *m = RawReverseScanResponse{} }
func (m *RawReverseScanResponse) String() string { return proto.CompactTextString(m) }
func (*RawReverseScanResponse) ProtoMessage()    {}
func (*RawReverseScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e61771abef0cd5d8, []int{17}
}

func (m *RawReverseScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawReverseScanResponse.Unmarshal(m, b)
}
func (m *RawReverseScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawReverseScanResponse.Marshal(b, m, deterministic)
}
func (m *RawReverseScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawReverseScanResponse.Merge(m, src)
}
func (m *RawReverseScanResponse) XXX_Size() int {
	return xxx_messageInfo_RawReverseScanResponse.Size(m)
}
func (m *RawReverseScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawReverseScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawReverseScanResponse proto.InternalMessageInfo

func (m *RawReverseScanResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RawReverseScanResponse) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *RawReverseScanResponse) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*RawGetRequest)(nil), "serverpb.RawGetRequest")
	proto.RegisterType((*RawGetResponse)(nil), "serverpb.RawGetResponse")
	proto.RegisterType((*RawBatchGetRequest)(nil), "serverpb.RawBatchGetRequest")
	proto.RegisterType((*RawBatchGetResponse)(nil), "serverpb.RawBatchGetResponse")
	proto.RegisterType((*RawPutRequest)(nil), "serverpb.RawPutRequest")
	proto.RegisterType((*RawPutResponse)(nil), "serverpb.RawPutResponse")
	proto.RegisterType((*RawBatchPutRequest)(nil), "serverpb.RawBatchPutRequest")
	proto.RegisterType((*RawBatchPutResponse)(nil), "serverpb.RawBatchPutResponse")
	proto.RegisterType((*RawDeleteRequest)(nil), "serverpb.RawDeleteRequest")
	proto.RegisterType((*RawDeleteResponse)(nil), "serverpb.RawDeleteResponse")
	proto.RegisterType((*RawBatchDeleteRequest)(nil), "serverpb.RawBatchDeleteRequest")
	proto.RegisterType((*RawBatchDeleteResponse)(nil), "serverpb.RawBatchDeleteResponse")
	proto.RegisterType((*RawDeleteRangeRequest)(nil), "serverpb.RawDeleteRangeRequest")
	proto.RegisterType((*RawDeleteRangeResponse)(nil), "serverpb.RawDeleteRangeResponse")
	proto.RegisterType((*RawScanRequest)(nil), "serverpb.RawScanRequest")
	proto.RegisterType((*RawScanResponse)(nil), "serverpb.RawScanResponse")
	proto.RegisterType((*RawReverseScanRequest)(nil), "serverpb.RawReverseScanRequest")
	proto.RegisterType((*RawReverseScanResponse)(nil), "serverpb.RawReverseScanResponse")
}

func init() { proto.RegisterFile("serverpb.proto", fileDescriptor_e61771abef0cd5d8) }

var fileDescriptor_e61771abef0cd5d8 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0xfb, 0x83, 0x75, 0xeb, 0xb1, 0x8d, 0x61, 0x60, 0x0b, 0x19, 0x13, 0xc5, 0x42, 0xa8,
	0x68, 0x52, 0x1f, 0xe0, 0x81, 0x17, 0x90, 0x26, 0x40, 0xf0, 0x30, 0x90, 0x2a, 0x0f, 0x5e, 0x10,
	0x12, 0xf2, 0xba, 0x13, 0x54, 0x2d, 0x49, 0xb1, 0xdd, 0x96, 0xfc, 0x5f, 0xfc, 0x81, 0xa8, 0x97,
	0x36, 0xb5, 0x5d, 0x27, 0x3c, 0x00, 0x6f, 0x71, 0xee, 0xf2, 0xf9, 0x7e, 0xcf, 0xbe, 0x73, 0x60,
	0x5f, 0xa3, 0x9a, 0xa1, 0x9a, 0x5c, 0xf6, 0x26, 0x2a, 0x35, 0x29, 0xdb, 0x59, 0xad, 0xf9, 0x03,
	0xd8, 0x13, 0x72, 0xfe, 0x16, 0x8d, 0xc0, 0x1f, 0x53, 0xd4, 0x86, 0x1d, 0x40, 0x73, 0x84, 0x59,
	0x54, 0xef, 0xd4, 0xbb, 0xbb, 0x62, 0xf1, 0xc8, 0x9f, 0xc3, 0xfe, 0x2a, 0x45, 0x4f, 0xd2, 0x44,
	0x23, 0xbb, 0x0d, 0x5b, 0xa8, 0x54, 0xaa, 0x28, 0xab, 0x2d, 0xf2, 0xc5, 0xe2, 0xed, 0x4c, 0x8e,
	0xa7, 0x18, 0x35, 0xe8, 0xdb, 0x7c, 0xc1, 0xbb, 0xc0, 0x84, 0x9c, 0xbf, 0x94, 0x66, 0xf0, 0xcd,
	0x52, 0x61, 0x70, 0x6d, 0x84, 0x99, 0x8e, 0xea, 0x9d, 0x66, 0x77, 0x57, 0xd0, 0x33, 0x7f, 0x05,
	0xb7, 0x9c, 0xcc, 0x4a, 0xb1, 0x43, 0x68, 0x11, 0x5f, 0x47, 0x0d, 0x42, 0x2c, 0x57, 0xfc, 0x19,
	0xd5, 0xd3, 0x9f, 0x96, 0xd7, 0x53, 0xe2, 0xf3, 0x11, 0x55, 0x49, 0x1f, 0x56, 0x09, 0xf3, 0xb3,
	0x75, 0x3d, 0x96, 0x4a, 0xa0, 0x9e, 0x52, 0x8b, 0xa7, 0xeb, 0x3a, 0xff, 0x2c, 0xf7, 0x10, 0x0e,
	0x84, 0x9c, 0xbf, 0xc6, 0x31, 0x1a, 0x2c, 0x3f, 0xa2, 0xc7, 0x70, 0xd3, 0xca, 0xaa, 0x04, 0x9e,
	0xc2, 0x9d, 0x95, 0xba, 0x4b, 0x0d, 0x1d, 0x49, 0x0f, 0x0e, 0xfd, 0xe4, 0x4a, 0xf8, 0x7b, 0x82,
	0x2f, 0x53, 0x65, 0xf2, 0xb5, 0x80, 0x1f, 0x43, 0x5b, 0x1b, 0xa9, 0xcc, 0x97, 0xb5, 0xf1, 0x1d,
	0x7a, 0x71, 0x8e, 0x19, 0x3b, 0x82, 0x6d, 0x4c, 0xae, 0x28, 0x94, 0x1f, 0x49, 0x0b, 0x93, 0xab,
	0x73, 0xcc, 0x96, 0xf2, 0x0e, 0xae, 0x52, 0xfe, 0x33, 0x9d, 0xe1, 0xc5, 0x40, 0x26, 0x7f, 0xa5,
	0xbb, 0xa0, 0x8f, 0x87, 0xdf, 0x87, 0x26, 0x6a, 0x76, 0xea, 0xdd, 0x3d, 0x91, 0x2f, 0xf8, 0x05,
	0xdc, 0x28, 0xe8, 0x95, 0xbd, 0xb9, 0xda, 0xc9, 0x46, 0xb0, 0x19, 0x9a, 0x4e, 0x33, 0x0c, 0x68,
	0xc7, 0x04, 0xce, 0x50, 0x69, 0xfc, 0x5f, 0xce, 0x3f, 0xd1, 0x3e, 0x3a, 0x22, 0xff, 0xaa, 0x80,
	0x27, 0xbf, 0xb6, 0xa0, 0xfd, 0x61, 0x38, 0x9a, 0xf5, 0x55, 0xfa, 0x33, 0x63, 0x2f, 0xa0, 0x95,
	0xdf, 0x15, 0xec, 0xa8, 0x57, 0xdc, 0x39, 0xce, 0x05, 0x13, 0x47, 0x9b, 0x81, 0xdc, 0x0c, 0xaf,
	0xb1, 0x77, 0x70, 0xdd, 0xba, 0x02, 0xd8, 0x3d, 0x27, 0xd5, 0xbb, 0x43, 0xe2, 0x93, 0x92, 0x68,
	0x41, 0xcb, 0xcd, 0xf4, 0xa7, 0xbe, 0x99, 0xf5, 0xdc, 0x7a, 0x66, 0xac, 0x71, 0x74, 0xcd, 0x2c,
	0x18, 0x01, 0x33, 0x16, 0xe8, 0xa4, 0x24, 0x5a, 0xd0, 0xde, 0x40, 0xbb, 0xe8, 0x65, 0x16, 0x3b,
	0xd9, 0xce, 0x1c, 0xc6, 0xc7, 0xc1, 0x58, 0xc1, 0xf9, 0x48, 0x3d, 0x6e, 0x8d, 0x24, 0xbb, 0xbf,
	0x29, 0xed, 0x12, 0x3b, 0xe5, 0x09, 0x1e, 0xd6, 0x1a, 0x35, 0x0f, 0xbb, 0x39, 0xd3, 0x1e, 0x36,
	0x30, 0xa5, 0xbc, 0xc6, 0xce, 0x60, 0x7b, 0x39, 0x33, 0xcc, 0xdd, 0x6a, 0xab, 0xd5, 0xe3, 0xbb,
	0x81, 0x88, 0x67, 0xcc, 0xea, 0x5d, 0xcf, 0xd8, 0xe6, 0xe8, 0x78, 0xc6, 0x02, 0x6d, 0xcf, 0x6b,
	0x97, 0x2d, 0xfa, 0x11, 0x3e, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x93, 0x1c, 0x68, 0xa3, 0x1a,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TikvProxyClient is the client API for TikvProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TikvProxyClient interface {
	// RawKV commands
	RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error)
	RawBatchGet(ctx context.Context, in *RawBatchGetRequest, opts ...grpc.CallOption) (*RawBatchGetResponse, error)
	RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error)
	RawBatchPut(ctx context.Context, in *RawBatchPutRequest, opts ...grpc.CallOption) (*RawBatchPutResponse, error)
	RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error)
	RawBatchDelete(ctx context.Context, in *RawBatchDeleteRequest, opts ...grpc.CallOption) (*RawBatchDeleteResponse, error)
	RawDeleteRange(ctx context.Context, in *RawDeleteRangeRequest, opts ...grpc.CallOption) (*RawDeleteRangeResponse, error)
	RawScan(ctx context.Context, in *RawScanRequest, opts ...grpc.CallOption) (*RawScanResponse, error)
	RawReverseScan(ctx context.Context, in *RawReverseScanRequest, opts ...grpc.CallOption) (*RawReverseScanResponse, error)
}

type tikvProxyClient struct {
	cc *grpc.ClientConn
}

func NewTikvProxyClient(cc *grpc.ClientConn) TikvProxyClient {
	return &tikvProxyClient{cc}
}

func (c *tikvProxyClient) RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error) {
	out := new(RawGetResponse)
	err := c.cc.Invoke(ctx, "/serverpb.TikvProxy/RawGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvProxyClient) RawBatchGet(ctx context.Context, in *RawBatchGetRequest, opts ...grpc.CallOption) (*RawBatchGetResponse, error) {
	out := new(RawBatchGetResponse)
	err := c.cc.Invoke(ctx, "/serverpb.TikvProxy/RawBatchGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvProxyClient) RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error) {
	out := new(RawPutResponse)
	err := c.cc.Invoke(ctx, "/serverpb.TikvProxy/RawPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvProxyClient) RawBatchPut(ctx context.Context, in *RawBatchPutRequest, opts ...grpc.CallOption) (*RawBatchPutResponse, error) {
	out := new(RawBatchPutResponse)
	err := c.cc.Invoke(ctx, "/serverpb.TikvProxy/RawBatchPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvProxyClient) RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error) {
	out := new(RawDeleteResponse)
	err := c.cc.Invoke(ctx, "/serverpb.TikvProxy/RawDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvProxyClient) RawBatchDelete(ctx context.Context, in *RawBatchDeleteRequest, opts ...grpc.CallOption) (*RawBatchDeleteResponse, error) {
	out := new(RawBatchDeleteResponse)
	err := c.cc.Invoke(ctx, "/serverpb.TikvProxy/RawBatchDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvProxyClient) RawDeleteRange(ctx context.Context, in *RawDeleteRangeRequest, opts ...grpc.CallOption) (*RawDeleteRangeResponse, error) {
	out := new(RawDeleteRangeResponse)
	err := c.cc.Invoke(ctx, "/serverpb.TikvProxy/RawDeleteRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvProxyClient) RawScan(ctx context.Context, in *RawScanRequest, opts ...grpc.CallOption) (*RawScanResponse, error) {
	out := new(RawScanResponse)
	err := c.cc.Invoke(ctx, "/serverpb.TikvProxy/RawScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvProxyClient) RawReverseScan(ctx context.Context, in *RawReverseScanRequest, opts ...grpc.CallOption) (*RawReverseScanResponse, error) {
	out := new(RawReverseScanResponse)
	err := c.cc.Invoke(ctx, "/serverpb.TikvProxy/RawReverseScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TikvProxyServer is the server API for TikvProxy service.
type TikvProxyServer interface {
	// RawKV commands
	RawGet(context.Context, *RawGetRequest) (*RawGetResponse, error)
	RawBatchGet(context.Context, *RawBatchGetRequest) (*RawBatchGetResponse, error)
	RawPut(context.Context, *RawPutRequest) (*RawPutResponse, error)
	RawBatchPut(context.Context, *RawBatchPutRequest) (*RawBatchPutResponse, error)
	RawDelete(context.Context, *RawDeleteRequest) (*RawDeleteResponse, error)
	RawBatchDelete(context.Context, *RawBatchDeleteRequest) (*RawBatchDeleteResponse, error)
	RawDeleteRange(context.Context, *RawDeleteRangeRequest) (*RawDeleteRangeResponse, error)
	RawScan(context.Context, *RawScanRequest) (*RawScanResponse, error)
	RawReverseScan(context.Context, *RawReverseScanRequest) (*RawReverseScanResponse, error)
}

// UnimplementedTikvProxyServer can be embedded to have forward compatible implementations.
type UnimplementedTikvProxyServer struct {
}

func (*UnimplementedTikvProxyServer) RawGet(ctx context.Context, req *RawGetRequest) (*RawGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawGet not implemented")
}
func (*UnimplementedTikvProxyServer) RawBatchGet(ctx context.Context, req *RawBatchGetRequest) (*RawBatchGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawBatchGet not implemented")
}
func (*UnimplementedTikvProxyServer) RawPut(ctx context.Context, req *RawPutRequest) (*RawPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawPut not implemented")
}
func (*UnimplementedTikvProxyServer) RawBatchPut(ctx context.Context, req *RawBatchPutRequest) (*RawBatchPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawBatchPut not implemented")
}
func (*UnimplementedTikvProxyServer) RawDelete(ctx context.Context, req *RawDeleteRequest) (*RawDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawDelete not implemented")
}
func (*UnimplementedTikvProxyServer) RawBatchDelete(ctx context.Context, req *RawBatchDeleteRequest) (*RawBatchDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawBatchDelete not implemented")
}
func (*UnimplementedTikvProxyServer) RawDeleteRange(ctx context.Context, req *RawDeleteRangeRequest) (*RawDeleteRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawDeleteRange not implemented")
}
func (*UnimplementedTikvProxyServer) RawScan(ctx context.Context, req *RawScanRequest) (*RawScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawScan not implemented")
}
func (*UnimplementedTikvProxyServer) RawReverseScan(ctx context.Context, req *RawReverseScanRequest) (*RawReverseScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawReverseScan not implemented")
}

func RegisterTikvProxyServer(s *grpc.Server, srv TikvProxyServer) {
	s.RegisterService(&_TikvProxy_serviceDesc, srv)
}

func _TikvProxy_RawGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvProxyServer).RawGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.TikvProxy/RawGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvProxyServer).RawGet(ctx, req.(*RawGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TikvProxy_RawBatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawBatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvProxyServer).RawBatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.TikvProxy/RawBatchGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvProxyServer).RawBatchGet(ctx, req.(*RawBatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TikvProxy_RawPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvProxyServer).RawPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.TikvProxy/RawPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvProxyServer).RawPut(ctx, req.(*RawPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TikvProxy_RawBatchPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawBatchPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvProxyServer).RawBatchPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.TikvProxy/RawBatchPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvProxyServer).RawBatchPut(ctx, req.(*RawBatchPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TikvProxy_RawDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvProxyServer).RawDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.TikvProxy/RawDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvProxyServer).RawDelete(ctx, req.(*RawDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TikvProxy_RawBatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawBatchDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvProxyServer).RawBatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.TikvProxy/RawBatchDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvProxyServer).RawBatchDelete(ctx, req.(*RawBatchDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TikvProxy_RawDeleteRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawDeleteRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvProxyServer).RawDeleteRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.TikvProxy/RawDeleteRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvProxyServer).RawDeleteRange(ctx, req.(*RawDeleteRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TikvProxy_RawScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvProxyServer).RawScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.TikvProxy/RawScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvProxyServer).RawScan(ctx, req.(*RawScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TikvProxy_RawReverseScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawReverseScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvProxyServer).RawReverseScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.TikvProxy/RawReverseScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvProxyServer).RawReverseScan(ctx, req.(*RawReverseScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TikvProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.TikvProxy",
	HandlerType: (*TikvProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RawGet",
			Handler:    _TikvProxy_RawGet_Handler,
		},
		{
			MethodName: "RawBatchGet",
			Handler:    _TikvProxy_RawBatchGet_Handler,
		},
		{
			MethodName: "RawPut",
			Handler:    _TikvProxy_RawPut_Handler,
		},
		{
			MethodName: "RawBatchPut",
			Handler:    _TikvProxy_RawBatchPut_Handler,
		},
		{
			MethodName: "RawDelete",
			Handler:    _TikvProxy_RawDelete_Handler,
		},
		{
			MethodName: "RawBatchDelete",
			Handler:    _TikvProxy_RawBatchDelete_Handler,
		},
		{
			MethodName: "RawDeleteRange",
			Handler:    _TikvProxy_RawDeleteRange_Handler,
		},
		{
			MethodName: "RawScan",
			Handler:    _TikvProxy_RawScan_Handler,
		},
		{
			MethodName: "RawReverseScan",
			Handler:    _TikvProxy_RawReverseScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serverpb.proto",
}
